spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: 628760597fb0cd92a95a 
            client-secret: edb939873429436885a1ddcea0fd83da855ed71b
 # security:
  #  user:
   #   name: tij
    #  password: passer

  datasource:
    url: jdbc:postgresql://localhost:5432/mydb_sec?currentSchema=public
    username: postgres
    password: passer
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql:true

server:
  port: 8083